[package]
name = "xpm-pacman"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "Pacman configuration parsing for xPackageManager"
repository.workspace = true

[dependencies]
